### PR TITLE
compat laposte v2

### PR DESCRIPTION
**Pull request by DylannCordel**
laposte has published a v2 of it's API some years ago (2018 at least ?). This document refers to some changes which have been made between v1 and v2 :
[spec_ws_affranchissement_2018.pdf](https://github.com/akretion/roulier/files/5723686/spec_ws_affranchissement_2018.pdf)

This PR adds the ability to use v2 or the v1, (end-developper's choice) but keep in common 99% of the code (even for the tests).

### CODE REVIEW

**Comment by DylannCordel** [comment]
But... Do we need to keep v1 ?

**Comment by florian-dacosta** [comment]
I was not aware of this second version.
I don't think there is a point in maintaing both, I guess v1 is outdated compared to v2..
So I'd rather make the change to maintain only v2, keeping only laposte_fr carrier, like today, instead of adding a laposte_fr_v2.

Also, I know that now laposte manage a REST api. We do not really have time to switch from the soap to the REST now, but it is something that could be nice one day. But same, I don't think we should maintain both...

Would you make the change to maintain only v2 and drop v1 support ?
Are you sure any company with la poste account can switch from v1 to v2 overnight with not problem (on la poste side?)

**Comment by DylannCordel** [comment]
> Are you sure any company with la poste account can switch from v1 to v2 overnight with not problem (on la poste side?)

I think it is. Inside the doc, p10 :  
> La version 2 du Web Service d’Affranchissement est désormais effective et reprend toutes les fonctionnalités de la version 1. Nous vous suggérons d’utiliser cette nouvelle version.

Which means :   
> Version 2 of the Web Service is now effective and includes all the features of version 1. We suggest that you use this new version.

> Would you make the change to maintain only v2 and drop v1 support ?  

Sure, I'll rebase with master and update the PR to do that.

**Comment by florian-dacosta** [comment]
Thanks, simpler this way :)

All went fine with a test with a delivery in France (continent)
But then I did a test with an address in Guadeloupe (testing https://github.com/akretion/roulier/pull/135 altogether)
And I had an error : 
`rep.fields` give me `AttributeError: no such child: fields`

I guess this fields response is kind of optional (commenting it, all went fine, I got my label and cn23 pdf)
Could you test if `<fields>` tag is present before adding it? I guess it is not mandatory for them to fill this part...
What do you think?

**Comment by rvalyi** [comment]
@florian-dacosta @DylannCordel you guys absolutely need to check if the new Python xsdata SOAP lib doesn`t do the job for you.
It seems to deal with Laposte wsdl and embeded xsd very well from a quick test.
I tried:
```
xsdata --wsdl --package laposte https://ws.colissimo.fr/sls-ws/SlsServiceWS/2.0?wsdl
```

and I code this clean DRY code:
https://gist.github.com/rvalyi/aadf676b384c3f2040e45d37d062bfc7

I didn`t test further using it (see the doc), but I can assure you xsdata is a revoltion for our Brazilian electronic invoicing which is the most complex SOAP thing I have ever seen so I really doubt it`s not going to do the job for Laposte annd other Roulier providers. Even in the case you use it only for marshalling and unmarshalling the XML it`s probably already a win over incomplete and error prone manual code you then have to maintain...

cc @hparfr @bealdav @sebastienbeau

**Comment by DylannCordel** [comment]
Thanks @rvalyi 

As we have not so many code for laposte, IMHO, if we need to spend time on it, it will be preferable to refactor the code to use the REST service instead the old SOAP. Roulier has already it's own schema validation for inputs (with Cerberus) because there is not only SOAP/XML services which are used (and I hope there will be not anymore SOAP soon :D). GLS has it's own complicated format for exemple, laposte has a REST service now etc. But I'll keep xsdata in mind for other projects where we need to use XML, thanks !

@florian-dacosta optional fields is now fixed.

**Comment by florian-dacosta** [comment]
Indeed, if we have to refactore, we'd rather go with the REST service!
Thanks for the fix, LGTM now

**Pull request merged**
