### PR TITLE
IMP add xml_request in response

### PR DESCRIPTION
**Pull request by bealdav**
Return xml response to the client in case of debugging by laposte.

Webservice will evoluate.

Surprises should be detected by la poste not akretion.

Thanks to evaluate

### CODE REVIEW

**Comment by hparfr** [comment]
👎  
Should use logs for debug
It's adding more specific code for laposte while we need to unify all responses.

**Comment by bealdav** [comment]
The feature is: know what is the exact call to ws directly in the ERP to help debug with any soap tool

Here is the criterias:

1. Is this feature is required for an efficient support to customers
2. Should this feature be generic for all carriers.
3. Is there so many additional code 

For me:
1. Yes
2. Yes
3. Yes

Please @bguillot could you put your lights in this PR, thanks.

**Comment by bealdav** [comment]
Another solution could be to implement an 'dry run' to get xml without to really call the ws.

What do you think ?

**Comment by bguillot** [comment]
a dry run mode is a good idea but what output you get ?
display log and create a logfile on file system ?

**Comment by bealdav** [comment]
just a raise

**Comment by bguillot** [comment]
good idea

**Pull request closed without merging**
