### PR TITLE
migrate DPD to new roulier and python 3

### PR DESCRIPTION
**Pull request by DylannCordel**
`dpd` has been renamed to `dpd_fr_soap` because this webservice is specific to France (and `_soap` as discussed in #138 and #140). I also have a `dpd_sk_rest` available if someone is interrested but I don't have any credentials to test it (it seems each country have it's own webservice)

### CODE REVIEW

**Comment by DylannCordel** [comment]
@florian-dacosta PR is ready to be reviewed. If you want to run tests, you need to ask to DPD France they allow your IP to access their test server.

**Comment by florian-dacosta** [comment]
Thanks for your work again.
For you information, DPD should change its webservice. It was planned for 2019 though, but they were not ready, but they still should do it sooner or later.
Here is the work that was done to meet their new webservice : https://github.com/akretion/roulier/tree/feat/dpd_2019
Not used yet, just so you know. We will probably need to switch when they will be ready.

**Comment by DylannCordel** [comment]
@florian-dacosta code rebased and dpd_fr renamed to dpd_fr_rest (as discussed in #138 and #140)

**Comment by florian-dacosta** [comment]
@DylannCordel 
I didnt notice the PR was not up to date with master.
Merging it did break it because the last refactore here : https://github.com/akretion/roulier/commit/ba5640c2a1599b2ebff10e09577d74d52cbdd54a#diff-e2b8c9f0fa9c6966e5cb30dd546c57d799f60206afda0c7e15c85b915020bc8aR15

I made a fix, so all should be ok. But please, be careful if you update roulier and switch back to master for DPD, you should first confirm all is working properly.

**Comment by DylannCordel** [comment]
@florian-dacosta LGFM : tests are running from an allowed IP. We may ask to DPD to allow [travis IPs](https://docs.travis-ci.com/user/ip-addresses/) for the test account or create a specific test account for roulier ?

**Pull request merged**
