### PR TITLE
remove useless old py27 # -*- coding: utf-8 -*-

### PR DESCRIPTION
**Pull request by DylannCordel**
some cleanup of old python 2.7 comment to set the charset used for files. In py3, charset is utf8 by default.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by florian-dacosta** [comment]
@DylannCordel We use pre-commit with some black config to format the code.
If you can run it to fix the linting issues, it would be great.

**Comment by DylannCordel** [comment]
@florian-dacosta done, but strange travis error I don't understand.

**Comment by DylannCordel** [comment]
@florian-dacosta the error seems to come from master. It occurs on my 3 PR I just rebased. Maybe due to travis environnement because I dint get this error on my local machine.

**Comment by florian-dacosta** [comment]
How fast! Thanks
Yes, I saw this error, it occured when I merged a PR earlier today, but seems unrelatd to the merged PR.
I'll try to fix it

**Comment by florian-dacosta** [comment]
@DylannCordel 
Seems that this is the jinja2 recent version that were an issue. If froze it for now to avoid the issue.

**Pull request merged**
